### ISSUE TITLE
[Question]How is determine Fc

### ISSUE THREAD

**Issue by NitrofMtl** [overlord1123/DigitalFilters#1]
Hi. I'm neophyte in digital filtering.

I'm in try to adapt you're library for arduino.

But in you're example:

````
	constexpr float dtUsed = 0.01;
	// Construct various filter with cutoff frequency of 0.5 Hz.
	LowPassFilter lpf1(dtUsed, M_PI);
````

dt is the sample rate ?? and how in determine the cutoff frequency ?

Thanks.

Nitrof

**Comment by jimmyberg** [comment]
Hi

The first argument is the sample time e.g. 100hz is a sample time of 0.01
seconds.

The second argument is the angular cutoff frequency = 2 *pi * cutoff
frequency.

Good luck with your coding.
BTW what are you working on?

Kind regards,
Jimmy van den Berg BSc

Op ma 17 feb. 2020 19:42 schreef NitrofMtl <notifications@github.com>:

**Comment by NitrofMtl** [comment]
I'm trying do do a digital audio-cross over with the arduino DUE.
Seems clears now !

you maybe should make you example more clear y defining all the variables:
````
int fc= 50; //cut off
LowPassFilter lpf1(dtUsed, fc * 2 *M_PI);
````

BTW, to make it work, I mostly just remove the throw functions, and change one return statement in circularDelay:

````
template<typename type, size_t size>
type CircularDelay<type, size>::get(size_t delay){
	if(delay >= size + 1)
		//throw(std::domain_error("Tried to get a value that is longer ago than the size of a CircularDelay."));
	//reverse_iterator itRBegin(rbegin());
	//return itRBegin[delay];  // the return statement was strangely error itRBegin undefine... 
	return 	reverse_iterator(rbegin())[delay];
}
```` 


Thanks for the quick response.
